### ISSUE TITLE
GFortran 7.3.0 compiler error (Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by guidokanschat** [oseledets/ttpy#63] opened 2018-07-06 08:10 UTC
When trying to install ttpy on Ubuntu 18.04 LTS, I run into the following internal error of GFortran 7.3.0:

```
    gfortran:f90: tt/tt-fort/print/dispmodule.f90
    tt/tt-fort/print/dispmodule.f90:1248:0:
    
         character(widthmax_dint(x, fmt)) :: sa(size(x))
    
    internal compiler error: in conv_function_val, at fortran/trans-expr.c:3717
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    tt/tt-fort/print/dispmodule.f90:1248:0:
    
         character(widthmax_dint(x, fmt)) :: sa(size(x))
    
    internal compiler error: in conv_function_val, at fortran/trans-expr.c:3717
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -I/usr/lib/python2.7/dist-packages/numpy/core/include -Ibuild/temp.linux-x86_64-2.7 -Ibuild/temp.linux-x86_64-2.7 -Ibuild/temp.linux-x86_64-2.7 -I/usr/include/python2.7 -c -c tt/tt-fort/print/dispmodule.f90 -o build/temp.linux-x86_64-2.7/tt/tt-fort/print/dispmodule.o -Jbuild/temp.linux-x86_64-2.7 -Ibuild/temp.linux-x86_64-2.7" failed with exit status 1
```

This happens with pip install as well as with manual install of the cloned sources. I am not sure if you want to fix this or wait, though.

**Comment by daskol** [comment] 2018-07-06 12:28
Duplicate of #60. Try to compile with gfortran newer than 6.0 or older than 9.0 or use other Fortran compiler.

**Closed by daskol** 2018-07-06 12:28 UTC
